[package]
name = "annp-model"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["cuda"]
cuda = ["annp-cuda/cuda"]

[dependencies]
annp-core = { path = "../annp-core" }
annp-cuda = { path = "../annp-cuda" }
candle-core.workspace = true
candle-nn.workspace = true
serde.workspace = true
rand.workspace = true
dtact.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
annp-trainer = { path = "../annp-trainer" }
